### ISSUE TITLE
Help?

### ISSUE THREAD

**Issue by JInnyboii** [rivor/fortnite-scrim-bot#29]
Help?

Error: Cannot find module 'C:\Users\johan\Downloads\fortnite-scrim-bot-master\bot'
[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:859:27)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m {
  code: [32m'MODULE_NOT_FOUND'[39m,
  requireStack: []
}

**Comment by rivor** [comment]
Hey, it's a late reply but i guess it's fine. :D 

This bot is outdated, and i don't really see a need for updating it as Fortnite supports custom games anyway. This bot was targeted for communities that are large enough that could get the custom game access anyway. But i haven't played Fortnite in a very long time, so i'm not sure how it's going there with those custom game accesses.

Either way, for me to update this bot. I would need quite decent amount of people interested. Then i'd be down to do it and implement even more features.
